services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "url-storage"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "passwd"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./assets/postgres/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
volumes:
  pgdata: