env: "local" # (local, prod)
postgres_server:
  address: "localhost"
  port: "5432"
  user: "user"
  password: "pass"
  db_name: "url-storage"
http_server:
  address: "localhost"
  port: "8080"
  timeout: 4s
  idle_timeout: 60s