env: "local" # (local, prod)
alias_len: 8
shutdown_timeout: 5s
postgres_server:
  address: "localhost"
  port: "5432"
  user: "user"
  password: "passwd"
  db_name: "url-storage"
http_server:
  address: "localhost"
  port: "8080"
  timeout: 4s
  idle_timeout: 60s