CREATE TABLE IF NOT EXISTS users
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS urls
(
    id SERIAL PRIMARY KEY,
    url VARCHAR(255) NOT NULL,
    alias VARCHAR(100) NOT NULL UNIQUE,
    user_id INT REFERENCES users (id) ON DELETE CASCADE NOT NULL
);